### ISSUE TITLE
why us dont use html-to-image

### ISSUE THREAD

**Issue by code-ga** [pdt1806/discord-status-as-image#3]
[html-to-image](https://www.npmjs.com/package/html-to-image)

**Comment by pdt1806** [comment]
Sorry for the late reply but basically if I used that package, I would have to store the images on the server for the images to be accessed later, and I don't want that, not to mention that the images are no longer "live." Puppeteer does a better job because when every time the URL of the image is accessed, a new, live image is served.

Happy Holidays :christmas_tree:
